import type { Config } from 'tailwindcss';
export default { content: ['./src/**/*.{ts,tsx}'], theme: { extend: { colors: {
  page:'rgb(var(--page-bg) / <alpha-value>)',
  section:'rgb(var(--section-bg) / <alpha-value>)',
  ink:'rgb(var(--page-bg) / <alpha-value>)',
  panel:'rgb(var(--section-bg) / <alpha-value>)',
  card:'rgb(var(--card-bg) / <alpha-value>)',
  elevated:'rgb(var(--elevated-bg) / <alpha-value>)',
  primary:'rgb(var(--text-primary) / <alpha-value>)',
  secondary:'rgb(var(--text-secondary) / <alpha-value>)',
  muted:'rgb(var(--text-muted) / <alpha-value>)',
  line:'var(--border-color)',
  cyan:'rgb(var(--accent) / <alpha-value>)',
  cyanHover:'rgb(var(--accent-hover) / <alpha-value>)',
  violet:'rgb(var(--accent-secondary) / <alpha-value>)',
  buttonPrimary:'rgb(var(--button-primary-bg) / <alpha-value>)',
  buttonPrimaryHover:'rgb(var(--button-primary-hover-bg) / <alpha-value>)',
  buttonPrimaryText:'rgb(var(--button-primary-text) / <alpha-value>)',
  buttonSecondary:'rgb(var(--button-secondary-bg) / <alpha-value>)',
  buttonSecondaryText:'rgb(var(--button-secondary-text) / <alpha-value>)',
  pill:'rgb(var(--pill-bg) / <alpha-value>)',
  pillBorder:'var(--pill-border)',
  nav:'rgb(var(--nav-bg) / <alpha-value>)',
  focus:'rgb(var(--focus-ring) / <alpha-value>)',
  heroPrimary:'rgb(var(--hero-text-primary) / <alpha-value>)',
  heroSecondary:'rgb(var(--hero-text-secondary) / <alpha-value>)',
  heroAccent:'rgb(var(--hero-accent) / <alpha-value>)',
  field:'rgb(var(--field-bg) / <alpha-value>)',
  disabled:'rgb(var(--disabled-bg) / <alpha-value>)',
  disabledText:'rgb(var(--disabled-text) / <alpha-value>)'
 }, boxShadow: { glow: 'var(--shadow-glow)', card: 'var(--shadow-card)' } } }, plugins: [] } satisfies Config;
